name: Flask App CI/CD Pipeline

on:
  workflow_dispatch:
#  push:
#    branches: [ "main" ]
#    paths:
#      - 'app/**'
#      - 'k8s/**'

env:
  AZURE_CONTAINER_REGISTRY: "acrdevlabnj32xl"   # Update with your ACR name
  RESOURCE_GROUP: "rg-enterprise-lab-dev"          # Your Azure resource group
  CLUSTER_NAME: "aks-dev-eastus-001"                 # Your AKS cluster name
  CONTAINER_NAME: "flask-app"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and Push to ACR via Azure CLI
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az acr build --registry ${{ env.AZURE_CONTAINER_REGISTRY }} --image ${{ env.CONTAINER_NAME }}:${{ github.sha }} ./app

    - name: Set AKS Cluster Context
      uses: azure/aks-set-context@v5
      with:
        resource-group: ${{ env.RESOURCE_GROUP }}
        cluster-name: ${{ env.CLUSTER_NAME }}

    - name: Deploy Manifests to AKS
      run: |
        # Dynamically inject the new image tag into your deployment yaml before applying
        sed -i 's|image:.*|image: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ github.sha }}|g' k8s/deployment.yaml
        
        kubectl apply -f k8s/
        kubectl rollout status deployment/flask-deployment
